### ISSUE TITLE
parameters -Sdeps  and -Scp are not handled correctly

### ISSUE THREAD

**Issue by frericksm** [frericksm/clj-windows#2]
1. Steps to reproduce
open a comannd prompt and execute 
`clj -Sdeps '{:deps {cider/cider-nrepl {:mvn/version "0.18.0-SNAPSHOT"} }}' -e '(require (quote cider-nrepl.main)) (cider-nrepl.main/init ["cider.nrepl/cider-middleware"])'`
2. Expected result
`nREPL server started on port ....`
3. Actual result
`Exception in thread "main" java.io.FileNotFoundException: '{:deps (Das System kann die angegebene Datei nicht finden)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at clojure.lang.Compiler.loadFile(Compiler.java:7449)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$script_opt.invokeStatic(main.clj:338)
        at clojure.main$script_opt.invoke(main.clj:333)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)`
4. Environment 
4.1 OS WINDOWS 10
4.2 https://github.com/frericksm/clj-windows/releases/tag/v1.0-alpha installed

**Comment by frericksm** [comment]
https://github.com/frericksm/clj-windows/commit/a2c59378baa574128de7f84312da32f368d26e09
